name: Deploy a Cliente USA (SFTP)

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy USA
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Obtener cÃ³digo mÃ¡s reciente
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ðŸ“‚ Sincronizar archivos SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: access-5015726610.ud-webspace.de
          username: a124214
          password: (Cr3at3b1u3.MX!!)
          port: 22
          # Apuntamos a la carpeta USA sin la "/" inicial
          remote_path: CreatblueDemoUsa/wp-content/themes/child-theme/
